apiVersion: v2
name: splunk-enterprise
description: A Helm chart for Splunk Enterprise managed by the Splunk Operator that can be deployed with Palantir FedStart

type: application

version: 3.1.9

dependencies:
  - condition: splunk-operator.enabled
    name: splunk-operator
    repository: file://charts/splunk-operator
    version: 2.5.4
