version: 1
merge:
  trigger:
    labels: ["merge when ready"]
  ignore:
    labels: ["do not merge", "needs testing"]
  method: squash
  options:
    squash:
      body: pull_request_body
      message_delimiter: ==COMMIT_MSG==
  delete_after_merge: true
