apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-aws-s3-config
  labels:
    {{- include "loki.labels" .Subcharts.loki | nindent 4 }}
data:
  AWS_DEFAULT_REGION: {{ .Values.loki.loki.storage.s3.region }}
  AWS_ROLE_ARN: {{ .Values.fedstart.s3.aws_role_arn }}
  AWS_USE_FIPS_ENDPOINT: {{ quote .Values.fedstart.s3.aws_use_fips }}
  AWS_WEB_IDENTITY_TOKEN_FILE: "/var/run/secrets/kubernetes.io/serviceaccount/token"
---
