# See https://github.com/helm/chart-testing#configuration
remote: origin
target-branch: develop
debug: true
validate-maintainers: false
helm-lint-extra-args: '--strict'
chart-dirs:
  - charts/alpha
  - charts/beta
  - charts/ga
chart-repos:
# Repos get generated at CI time dynamically, see .github/workflows/lint.yaml
