# See https://github.com/helm/chart-testing#configuration
remote: origin
target-branch: develop
debug: true
validate-maintainers: false
helm-lint-extra-args: '--strict'
chart-dirs:
  - charts/alpha
  - charts/beta
  - charts/ga
chart-repos:
  - grafana=https://grafana.github.io/helm-charts
  - prometheus=https://prometheus-community.github.io/helm-charts
  - vector=https://helm.vector.dev
