# See https://github.com/helm/chart-testing#configuration
remote: origin
target-branch: develop
debug: true
validate-maintainers: false
chart-dirs:
  - charts/alpha
  - charts/beta
  - charts/ga
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami
  - grafana=https://grafana.github.io/helm-charts
  - prometheus-community=https://prometheus-community.github.io/helm-charts
  - vector=https://helm.vector.dev
