keycloak:
  networkPolicy:
    enabled: false

  postgresql:
    enabled: false

  externalDatabase:
    existingSecret: "secret"

  containerSecurityContext:
    seLinuxOptions: null

  service:
    headless:
      annotations:
        com.palantir.rubix.service/pod-cert: '{}'
    annotations:
      com.palantir.rubix.service/pod-cert: '{"additionalOutputFormats":["JKS"]}'

  tls:
    enabled: true
    existingSecret: "cert-{{ .Release.Name }}"
    truststoreFilename: truststore.jks
    keystoreFilename: keystore.jks

  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/name: keycloak
            topologyKey: topology.kubernetes.io/zone
          weight: 100
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/name: keycloak
          topologyKey: kubernetes.io/hostname
