keycloak:
  replicaCount: 1

  auth:
    existingSecret: ""
    passwordSecretKey: password
    adminUser: "admin"

  networkPolicy:
    enabled: false

  postgresql:
    enabled: false
    primary:
      networkPolicy:
        enabled: false
      containerSecurityContext:
        seLinuxOptions: null


  externalDatabase:
    existingSecret: "secret"
    existingSecretDatabaseKey: ""
    existingSecretHostKey: ""
    existingSecretPasswordKey: ""
    existingSecretPortKey: ""
    existingSecretUserKey: ""

  httpRelativePath: "/keycloak/"
  containerSecurityContext:
    seLinuxOptions: null

  service:
    annotations:
      com.palantir.rubix.service/pod-cert: '{}'
    ports:
      https: 8443

  tls:
    enabled: true
    existingSecret: "cert-{{ .Release.Name }}"
    truststoreFilename: truststore.jks
    keystoreFilename: keystore.jks
    keystorePassword: ""
    truststorePassword: ""

  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/name: keycloak
            topologyKey: topology.kubernetes.io/zone
          weight: 100
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - keycloak
          topologyKey: kubernetes.io/hostname

