apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "prometheus.server.labels" .Subcharts.prometheus | nindent 4 }}
  name: "prometheus-apollo-config"
data:
  prometheus-web-config.yml: |
    tls_server_config:
      cert_file: /mnt/secrets/certs/tls.crt
      key_file: /mnt/secrets/certs/tls.key
      client_ca_file: /etc/ssl/rubix-ca/ca.pem
      client_auth_type: VerifyClientCertIfGiven
      # required because Go's default for server is TLS v1.0 https://pkg.go.dev/crypto/tls#Config:~:text=and%20TLS%201.0%20when%20acting%20as%20a%20server
      min_version: "TLS12"
      cipher_suites:
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
        - TLS_CHACHA20_POLY1305_SHA256
        - TLS_AES_128_GCM_SHA256
        - TLS_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
