# Default values for prometheus.

## Subchart value overrides
prometheus:
  rbac:
    create: false

  # Disable scrapes by default
  scrapeConfigs:
    prometheus:
      enabled: false
    kubernetes-api-servers:
      enabled: false
    kubernetes-nodes:
      enabled: false
    kubernetes-nodes-cadvisor:
      enabled: false
    kubernetes-service-endpoints:
      enabled: false
    kubernetes-service-endpoints-slow:
      enabled: false
    prometheus-pushgateway:
      enabled: false
    kubernetes-services:
      enabled: false
    kubernetes-pods:
      enabled: false
    kubernetes-pods-slow:
      enabled: false

  server:
    # Override if using mirrored container images
    # image:
    #   repository: quay.io/prometheus/prometheus

    fullnameOverride: prometheus

    statefulSet:
      enabled: true
      headless:
        annotations:
          com.palantir.rubix.service/pod-cert: '{"staticReplicaCount":1}'

    persistentVolume:
      enabled: true
      size: 100Gi

    resources:
      requests:
        cpu: 500m
        memory: 1Gi

    extraFlags:
      - web.config.file=/etc/config/apollo/prometheus-web-config.yml
      - web.enable-remote-write-receiver
      # Retention size here should be kept consistent with PVC size. Make retention 80% of PVC size as retention based
      # on size is only done on WAL truncation
      - storage.tsdb.retention.size=80GB
      - log.format=json
      - log.level=info

    probeScheme: HTTPS
    extraConfigmapMounts:
      - name: prometheus-apollo-config
        mountPath: /etc/config/apollo
        configMap: prometheus-apollo-config

    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      seccompProfile:
        type: RuntimeDefault

    service:
      servicePort: 443
      annotations:
        com.palantir.rubix.service/pod-cert: '{"staticReplicaCount":1}'

    extraVolumeMounts:
      - name: cert-secret-volume
        mountPath: "/mnt/secrets/certs"
      - name: rubix-ca-bundle
        mountPath: "/etc/ssl/rubix-ca"

    extraVolumes:
      - name: cert-secret-volume
        secret:
          secretName: cert-prometheus-1
      - name: rubix-ca-bundle
        configMap:
          name: "tls-external-ca-pem-bundle"
          items:
            - key: ca.pem
              path: ca.pem
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: com.palantir.rubix/instance-group
                operator: In
                values:
                  - fedstart

  alertmanager:
    enabled: false

  configmapReload:
    prometheus:
      enabled: false

  kube-state-metrics:
    enabled: false

  prometheus-node-exporter:
    enabled: false

  prometheus-pushgateway:
    enabled: false
