apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    apollo-app: prometheus
  name: "prometheus-apollo-config"
data:
  prometheus-web-config.yml: |
    tls_server_config:
      cert_file: /mnt/secrets/certs/cert.pem
      key_file: /mnt/secrets/certs/key.pem
      client_ca_file: /etc/ssl/rubix-ca/ca.pem
      client_auth_type: VerifyClientCertIfGiven
      # required because Go's default for server is TLS v1.0 https://pkg.go.dev/crypto/tls#Config:~:text=and%20TLS%201.0%20when%20acting%20as%20a%20server
      min_version: "TLS12"
      cipher_suites:
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
        - TLS_RSA_WITH_AES_256_CBC_SHA
