name: Lint Charts

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Add helm repos to ct
        run: yq '.repositories[] |  (" - " + .name + "=" + .url)' helm-repositories.yaml >> .github/linters/ct.yaml

      - name: Run chart-testing (lint)
        run: ct lint --config .github/linters/ct.yaml

      - name: Run markdown lint
        uses: DavidAnson/markdownlint-cli2-action@v9
        with:
          config: .github/linters/.markdownlint-cli2.yaml
