{{- if .Values.splunkOperator.clusterWideAccess }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "splunk-operator.operator.fullname" . }}-licensemanager-editor-role
rules:
- apiGroups:
  - enterprise.splunk.com
  resources:
  - licensemanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - enterprise.splunk.com
  resources:
  - licensemanagers/status
  verbs:
  - get
{{- else }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "splunk-operator.operator.fullname" . }}-licensemanager-editor-role
rules:
- apiGroups:
  - enterprise.splunk.com
  resources:
  - licensemanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - enterprise.splunk.com
  resources:
  - licensemanagers/status
  verbs:
  - get
{{- end }}